<?php

namespace Database\Seeders;

use App\Domains\Core\Permission\Models\Permission;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('permissions')->delete();
        $updateDate = $createDate = date('Y-m-d H:i:s');
        $permissions = [
            // contant management
            [
                'name' => 'content_management_access',
                'title' => 'Access',
                'route_name' => 'pages',
                'type' => 'backend',
                'status' => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate
            ],
            [
                'name' => 'content_management_edit',
                'title' => 'Edit',
                'route_name' => 'pages',
                'type' => 'backend',
                'status' => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate
            ],
            [
                'name' => 'content_management_show',
                'title' => 'View',
                'route_name' => 'pages',
                'type' => 'backend',
                'status' => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            // Cities
            [
                'name'       => 'city_access',
                'title'      => 'Access',
                'route_name' => 'cities',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'city_create',
                'title'      => 'Create',
                'route_name' => 'cities',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'city_edit',
                'title'      => 'Edit',
                'route_name' => 'cities',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'city_show',
                'title'      => 'Show',
                'route_name' => 'cities',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'city_delete',
                'title'      => 'Delete',
                'route_name' => 'cities',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'city_import',
                'title'      => 'Import',
                'route_name' => 'cities',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            //Subciption package
            [
                'name'       => 'subscription_access',
                'title'      => 'Access',
                'route_name' => 'subscriptions',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'subscription_create',
                'title'      => 'Create',
                'route_name' => 'subscriptions',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'subscription_edit',
                'title'      => 'Edit',
                'route_name' => 'subscriptions',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'subscription_show',
                'title'      => 'Show',
                'route_name' => 'subscriptions',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'subscription_delete',
                'title'      => 'Delete',
                'route_name' => 'subscriptions',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // Subscribers
            [
                'name'       => 'subscriber_access',
                'title'      => 'Access',
                'route_name' => 'subscribers',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            // [
            //     'name'       => 'subscriber_edit',
            //     'title'      => 'Edit',
            //     'route_name' => 'subscribers',
            //     'type'       => 'backend',
            //     'status'        => 1,
            //     'created_at' => $createDate,
            //     'updated_at' => $updateDate,
            // ],
            [
                'name'       => 'subscriber_show',
                'title'      => 'Show',
                'route_name' => 'subscribers',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            // [
            //     'name'       => 'subscriber_delete',
            //     'title'      => 'Delete',
            //     'route_name' => 'subscribers',
            //     'type'       => 'backend',
            //     'status'        => 1,
            //     'created_at' => $createDate,
            //     'updated_at' => $updateDate,
            // ],

            // Specilities
            [
                'name'       => 'specialties_access',
                'title'      => 'Access',
                'route_name' => 'specialties',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'specialties_create',
                'title'      => 'Create',
                'route_name' => 'specialties',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'specialties_edit',
                'title'      => 'Edit',
                'route_name' => 'specialties',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'specialties_show',
                'title'      => 'Show',
                'route_name' => 'specialties',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'specialties_delete',
                'title'      => 'Delete',
                'route_name' => 'specialties',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // Specilities Request
            [
                'name'       => 'specialties_request_access',
                'title'      => 'Access',
                'route_name' => 'specialty_requests',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'specialties_request_show',
                'title'      => 'Show',
                'route_name' => 'specialty_requests',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'specialties_request_status',
                'title'      => 'Approve/Reject',
                'route_name' => 'specialty_requests',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // Customers
            [
                'name'       => 'customer_access',
                'title'      => 'Access',
                'route_name' => 'customers',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'customer_ban',
                'title'      => 'Ban/Unban',
                'route_name' => 'customers',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'customer_show',
                'title'      => 'Show',
                'route_name' => 'customers',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'customer_edit',
                'title'      => 'Edit',
                'route_name' => 'customers',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'customer_status', //active in-active
                'title'      => 'Status',
                'route_name' => 'customers',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'customer_delete',
                'title'      => 'Status',
                'route_name' => 'customers',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            

            // Masters
            [
                'name'       => 'master_access',
                'title'      => 'Access',
                'route_name' => 'masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'master_edit',
                'title'      => 'Edit',
                'route_name' => 'masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'master_show',
                'title'      => 'Show',
                'route_name' => 'masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'master_is_approve', // approve reject
                'title'      => 'Approve/Reject',
                'route_name' => 'masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'master_ban',
                'title'      => 'Ban/Unban',
                'route_name' => 'masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'master_status', // active in-active
                'title'      => 'Application Status',
                'route_name' => 'masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'master_delete',
                'title'      => 'Delete',
                'route_name' => 'masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // Verified Masters
            [
                'name'       => 'verified_master_access',
                'title'      => 'Access',
                'route_name' => 'verified_masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'verified_master_edit',
                'title'      => 'Edit',
                'route_name' => 'verified_masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'verified_master_show',
                'title'      => 'Show',
                'route_name' => 'verified_masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'verified_master_is_approve', // approve reject
                'title'      => 'Approve/Reject',
                'route_name' => 'verified_masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'verified_master_ban',
                'title'      => 'Ban/Unban',
                'route_name' => 'verified_masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'verified_master_status', // active in-active
                'title'      => 'Application Status',
                'route_name' => 'verified_masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'verified_master_delete',
                'title'      => 'Delete',
                'route_name' => 'verified_masters',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // Roles
            [
                'name'       => 'role_access',
                'title'      => 'Access',
                'route_name' => 'roles',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'role_create',
                'title'      => 'Create',
                'route_name' => 'roles',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'role_edit',
                'title'      => 'Edit',
                'route_name' => 'roles',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'role_show',
                'title'      => 'Show',
                'route_name' => 'roles',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'role_delete',
                'title'      => 'Delete',
                'route_name' => 'roles',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // Admins
            [
                'name'       => 'admin_access',
                'title'      => 'Access',
                'route_name' => 'admins',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'admin_create',
                'title'      => 'Create',
                'route_name' => 'admins',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'admin_edit',
                'title'      => 'Edit',
                'route_name' => 'admins',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'admin_show',
                'title'      => 'Show',
                'route_name' => 'admins',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'admin_delete',
                'title'      => 'Delete',
                'route_name' => 'admins',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'admin_change_password',
                'title'      => 'Change Password',
                'route_name' => 'admins',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // FAQ
            [
                'name'       => 'faq_access',
                'title'      => 'Access',
                'route_name' => 'faqs',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'faq_create',
                'title'      => 'Create',
                'route_name' => 'faqs',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'faq_edit',
                'title'      => 'Edit',
                'route_name' => 'faqs',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'faq_show',
                'title'      => 'Show',
                'route_name' => 'faqs',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'faq_delete',
                'title'      => 'Delete',
                'route_name' => 'faqs',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // contant in setting
            [
                'name'       => 'setting_access',
                'title'      => 'Access',
                'route_name' =>'settings',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'setting_edit',
                'title'      => 'Edit',
                'route_name' =>'settings',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'setting_show',
                'title'      => 'Show',
                'route_name' => 'settings',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // Splash Screen Settings
              [
                'name'       => 'splash_screen_access',
                'title'      => 'Access',
                'route_name' => 'splashes',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            // [
            //     'name'       => 'splash_screen_create',
            //     'title'      => 'Create',
            //     'route_name' => 'splashes',
            //     'type'       => 'backend',
            //     'status'        => 1,
            //     'created_at' => $createDate,
            //     'updated_at' => $updateDate,
            // ],
            [
                'name'       => 'splash_screen_edit',
                'title'      => 'Edit',
                'route_name' => 'splashes',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'splash_screen_show',
                'title'      => 'Show',
                'route_name' => 'splashes',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            // [
            //     'name'       => 'splash_screen_delete',
            //     'title'      => 'Delete',
            //     'route_name' => 'splashes',
            //     'type'       => 'backend',
            //     'status'        => 1,
            //     'created_at' => $createDate,
            //     'updated_at' => $updateDate,
            // ],

            // Subscription Plan
              [
                'name'       => 'plan_access',
                'title'      => 'Access',
                'route_name' => 'subscription-plans',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'plan_edit',
                'title'      => 'Edit',
                'route_name' => 'subscription-plans',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'plan_show',
                'title'      => 'Show',
                'route_name' => 'subscription-plans',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // Transaction
              [
                'name'       => 'transaction_access',
                'title'      => 'Access',
                'route_name' => 'transaction-plans',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'transaction_show',
                'title'      => 'Show',
                'route_name' => 'transaction-plans',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            // Announcement
             [
                'name'       => 'announcement_access',
                'title'      => 'Access',
                'route_name' => 'announcements',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'announcement_create',
                'title'      => 'Create',
                'route_name' => 'announcements',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'announcement_show',
                'title'      => 'Show',
                'route_name' => 'announcements',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'announcement_delete',
                'title'      => 'Delete',
                'route_name' => 'announcements',
                'type'       => 'backend',
                'status'        => 1,
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

        ];
        Permission::insert($permissions);
    }
}
