<?php

namespace Database\Seeders;

use App\Domains\Core\Setting\Models\Setting;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('settings')->delete();
        $settings = [
            [
                'key'           => 'site_title',
                'value'         => 'Wabell',
                'type'          => 'text',
                'display_name'  => 'Site Title',
                'group'         => 'web',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'site_logo',
                'value'         => null,
                'type'          => 'image',
                'details'       => null,
                'display_name'  => 'Site Logo',
                'group'         => 'web',
                'status'        => 1,
                'position'      => 2,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'auth_logo',
                'value'         => null,
                'type'          => 'image',
                'details'       => null,
                'display_name'  => 'Auth Page Logo',
                'group'         => 'web',
                'status'        => 1,
                'position'      => 2,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'favicon',
                'value'         => null,
                'type'          => 'image',
                'details'       => null,
                'display_name'  =>'Favicon Icon',
                'group'         => 'web',
                'status'        => 1,
                'position'      => 3,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'master_logo',
                'value'         => null,
                'type'          => 'image',
                'details'       => null,
                'display_name'  => 'Master Logo',
                'group'         => 'web',
                'status'        => 1,
                'position'      => 2,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'student_logo',
                'value'         => null,
                'type'          => 'image',
                'details'       => null,
                'display_name'  => 'Learner Logo',
                'group'         => 'web',
                'status'        => 1,
                'position'      => 2,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'about_us_en',
                'value'         => null,
                'type'          => 'text',
                'display_name'  => 'About Us En',
                'group'         => 'content',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'about_us_ar',
                'value'         => null,
                'type'          => 'text',
                'display_name'  => 'About Us Ar',
                'group'         => 'content',
                'details'       => null,
                'status'        => 1,
                'position'      => 2,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'term_condition_en',
                'value'         => null,
                'type'          => 'text',
                'display_name'  => 'Term & Condition En',
                'group'         => 'content',
                'details'       => null,
                'status'        => 1,
                'position'      => 3,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'term_condition_ar',
                'value'         => null,
                'type'          => 'text',
                'display_name'  => 'Term & Condition Ar',
                'group'         => 'content',
                'details'       => null,
                'status'        => 1,
                'position'      => 4,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'privacy_policy_en',
                'value'         => null,
                'type'          => 'text',
                'display_name'  => 'Privacy Policy En',
                'group'         => 'content',
                'details'       => null,
                'status'        => 1,
                'position'      => 5,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'privacy_policy_ar',
                'value'         => null,
                'type'          => 'text',
                'display_name'  => 'Privacy Policy Ar',
                'group'         => 'content',
                'details'       => null,
                'status'        => 1,
                'position'      => 6,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'support_email',
                'value'         => 'support@gmail.com',
                'type'          => 'text',
                'display_name'  => 'Email',
                'group'         => 'support',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'support_contact',
                'value'         => '98746563210',
                'type'          => 'text',
                'display_name'  => 'Phone',
                'group'         => 'support',
                'details'       => null,
                'status'        => 1,
                'position'      => 2,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'support_location_en',
                'value'         => 'KSA English',
                'type'          => 'text',
                'display_name'  => 'Location En',
                'group'         => 'support',
                'details'       => null,
                'status'        => 1,
                'position'      => 2,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'support_location_ar',
                'value'         => 'KSA Arabic',
                'type'          => 'text',
                'display_name'  => 'Location Ar',
                'group'         => 'support',
                'details'       => null,
                'status'        => 1,
                'position'      => 2,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'tutor_chat_status_cb',
                'value'         => 1,
                'type'          => 'boolean',
                'display_name'  => 'Master Chat Status',
                'group'         => 'global',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'social_link_youtube',
                'value'         => "https://www.youtube.com/",
                'type'          => 'text',
                'display_name'  => 'Youtube',
                'group'         => 'social_link',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'social_link_tiktok',
                'value'         => "https://www.tiktok.com/",
                'type'          => 'text',
                'display_name'  => 'Tiktok',
                'group'         => 'social_link',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'social_link_instagram',
                'value'         => "https://www.instagram.com/",
                'type'          => 'text',
                'display_name'  => 'Instagram',
                'group'         => 'social_link',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'social_link_linkedin',
                'value'         => "https://www.linkedin.com/",
                'type'          => 'text',
                'display_name'  => 'Linkedin',
                'group'         => 'social_link',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'social_link_snapchat',
                'value'         => "https://www.snapchat.com/",
                'type'          => 'text',
                'display_name'  => 'Snapchat',
                'group'         => 'social_link',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'social_link_twitter',
                'value'         => "https://x.com/i/flow/login",
                'type'          => 'text',
                'display_name'  => 'Twitter',
                'group'         => 'social_link',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'social_link_facebook',
                'value'         => "https://www.facebook.com/",
                'type'          => 'text',
                'display_name'  => 'Facebook',
                'group'         => 'social_link',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'social_link_whatsapp',
                'value'         => "https://www.whatsapp.com/",
                'type'          => 'text',
                'display_name'  => 'WhatsApp',
                'group'         => 'social_link',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'learner_welcome_video',
                'value'         => null,
                'type'          => 'image',
                'details'       => null,
                'display_name'  => 'Learner Welcome Video',
                'group'         => 'content',
                'status'        => 1,
                'position'      => 7,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'master_welcome_video',
                'value'         => null,
                'type'          => 'image',
                'details'       => null,
                'display_name'  => 'Master Welcome Video',
                'group'         => 'content',
                'status'        => 1,
                'position'      => 7,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'support_whatsapp_number',
                'value'         => "966500314943",
                'type'          => 'text',
                'display_name'  => 'Whatsapp Number',
                'group'         => 'support',
                'details'       => null,
                'status'        => 1,
                'position'      => 1,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'basic_site_info_en',
                'value'         => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
                'type'          => 'textarea',
                'details'       => null,
                'display_name'  => 'Basic Site Info English',
                'group'         => 'web',
                'status'        => 1,
                'position'      => 7,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
            [
                'key'           => 'basic_site_info_ar',
                'value'         => "لوريم إيبسوم دولور سيت أميت، consectetur adipiscing إيليت. Nunc vulputate libero et velit interdum، ac aliquet odio mattis. فئة مناسبة من النشاط الاجتماعي والعاطفي لكل منا، من خلال مفاهيم هيمينايوس.",
                'type'          => 'textarea',
                'details'       => null,
                'display_name'  => 'Basic Site Info Arabic',
                'group'         => 'web',
                'status'        => 1,
                'position'      => 7,
                'created_at'    => Carbon::now()->format('Y-m-d H:i:s'),
                'created_by'    => 1,
            ],
        ];
        Setting::insert($settings);
    }
}